// <auto-generated />
using System;
using IdentityAudit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityAudit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityAuditDbContext))]
    [Migration("20260804225946_AddAuditRulesAndEvaluations")]
    partial class AddAuditRulesAndEvaluations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityAudit.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ComplianceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Audits_TargetId_CreatedAt");

                    b.ToTable("Audits", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.AuditRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CisControl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_AuditRules_Code");

                    b.ToTable("AuditRules", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("GroupType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuditId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_DirectoryGroups_AuditId_ExternalId");

                    b.ToTable("DirectoryGroups", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsServiceAccount")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuditId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Identities", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsPrivileged")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuditId", "ExternalId")
                        .IsUnique();

                    b.ToTable("DirectoryRoles", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IdentityId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("IX_GroupMemberships_IdentityId_GroupId");

                    b.ToTable("GroupMemberships", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DirectoryRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryRoleId");

                    b.HasIndex("IdentityId", "DirectoryRoleId")
                        .IsUnique();

                    b.ToTable("RoleAssignments", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.RuleEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("FindingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRuleId");

                    b.HasIndex("AuditId", "AuditRuleId")
                        .IsUnique()
                        .HasDatabaseName("IX_RuleEvaluations_AuditId_AuditRuleId");

                    b.ToTable("RuleEvaluations", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastCollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Targets", (string)null);
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.Audit", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.Target", "Target")
                        .WithMany("Audits")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryGroup", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.Audit", "Audit")
                        .WithMany("Groups")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryIdentity", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.Audit", "Audit")
                        .WithMany("Identities")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryRole", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.Audit", "Audit")
                        .WithMany("Roles")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.DirectoryGroup", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityAudit.Domain.Entities.DirectoryIdentity", "Identity")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.RoleAssignment", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.DirectoryRole", "DirectoryRole")
                        .WithMany("Assignments")
                        .HasForeignKey("DirectoryRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityAudit.Domain.Entities.DirectoryIdentity", "Identity")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DirectoryRole");

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.RuleEvaluation", b =>
                {
                    b.HasOne("IdentityAudit.Domain.Entities.Audit", "Audit")
                        .WithMany("RuleEvaluations")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityAudit.Domain.Entities.AuditRule", "AuditRule")
                        .WithMany("Evaluations")
                        .HasForeignKey("AuditRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Audit");

                    b.Navigation("AuditRule");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.Audit", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Identities");

                    b.Navigation("Roles");

                    b.Navigation("RuleEvaluations");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.AuditRule", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryGroup", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryIdentity", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.DirectoryRole", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("IdentityAudit.Domain.Entities.Target", b =>
                {
                    b.Navigation("Audits");
                });
#pragma warning restore 612, 618
        }
    }
}
